DROP TRIGGER IF EXISTS insert_null_token&&&
CREATE TRIGGER insert_null_token AFTER INSERT ON USER_STORAGE
    FOR EACH ROW
    BEGIN
        INSERT INTO USER_TOKEN(USER_NAME) VALUE (NEW.USERNAME);
    END;&&&
